name: assemble
on: 
  push:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: download dasm
        run: wget https://github.com/dasm-assembler/dasm/releases/download/2.20.14/dasm-2.20.14-linux-x64.tar.gz
      - name: unpack dasm
        run: tar -xzf dasm-2.20.14-linux-x64.tar.gz
      - name: set executable
        run: chmod 700 dasm
      - name: assemble
        run: ./dasm *.asm -f3 -v0 -Ldigits.lst -sdigits.sym -odigits.bin
#      - name: delete latest release
#        if: ${{ github.event_name != 'release' }}
#        uses: dev-drprasad/delete-tag-and-release@v0.1.2
#        with:
#          delete_release: true
#          tag_name: last-push
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload binaries to last-push release
        if: ${{ github.event_name != 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: digits.*
          tag: last-push
          release_name: "files for last push"
          prerelease: true
          overwrite: true
          file_glob: true
      - name: upload binaries to created release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: digits.*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
