name: assemble
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: download dasm
        run: wget https://github.com/dasm-assembler/dasm/releases/download/2.20.14/dasm-2.20.14-linux-x64.tar.gz
      - name: unpack dasm
        run: tar -xzf dasm-2.20.14-linux-x64.tar.gz
      - name: set executable
        run: chmod 700 dasm
      - name: assemble
        run: ./dasm *.asm -f3 -v0 -Ldigits.lst -sdigits.sym -odigits.bin
      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: digits.*
          tag: r-$tag
          overwrite: true
          file_glob: true
  
